name: nasa_apod_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  transparent_image: ^1.0.0
  dio: ^3.0.10
  built_value:
  intl: ^0.16.1
  provider: ^4.3.3
  dio_http_cache: ^0.2.11
  cached_network_image: ^2.5.0
  photo_view: ^0.10.3
  image_downloader: ^0.20.1
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/

  fonts:
    - family: Rubik Regular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

    - family: Rubik Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf

    - family: Zilla Slab Light
      fonts:
        - asset: assets/fonts/ZillaSlab-Light.ttf
